import { FC } from 'react';
import Head from 'next/head';

type PageHeadProps = {
  title: string;
};

const PageHead: FC<PageHeadProps> = ({ title }) => (
  <Head>
    <title>{title}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default PageHead;
